version: "3.9"
services:
  test:
    build:
      context: .
      target: test
    image: myugen/ddd-go:test
    container_name: tavern-test
    tty: true
    networks:
      - default-net

networks:
  default-net:
    driver: bridge