version: "3.9"
services:
  app:
    build:
      context: .
      target: app
    image: myugen/ddd-go:dev
    container_name: ddd-go
    tty: true
    networks:
      - default-net

networks:
  default-net:
    driver: bridge